const quizzes = {
  
  music: [
    {
      id: 1,
      question: "Who is known as the King of Pop?",
      option1: "Elvis Presley",
      option2: "Michael Jackson",
      option3: "Freddie Mercury",
      option4: "Ed sheran",
      ans: 2,
      explain: "Michael Jackson earned the title for his global influence and record-breaking hits.",
      difficulty: "medium",
    },
    {
      id: 2,
      question: "Which band sang the hit song 'Bohemian Rhapsody'?",
      option1: "Queen",
      option2: "The Beatles",
      option3: "Pink Floyd",
      option4: "Led Zeppelin",
      ans: 1,
      explain: "Queen released 'Bohemian Rhapsody' in 1975 — it became one of the most iconic songs ever.",
      difficulty: "easy",
    },
    {
      id: 3,
      question: "Which artist released the album '25' in 2015?",
      option1: "Rihanna",
      option2: "Taylor Swift",
      option3: "Adele",
      option4: "Beyoncé",
      ans: 3,
      explain: "Adele’s album '25' included the hit single 'Hello'.",
      difficulty: "medium",
    },
    {
      id: 4,
      question: "Which instrument does a drummer play?",
      option1: "Guitar",
      option2: "Piano",
      option3: "Drums",
      option4: "Violin",
      ans: 3,
      explain: "The drummer plays the drums — they keep the rhythm in a band.",
      difficulty: "easy",
    },
    {
      id: 5,
      question: "Who wrote the song 'Imagine'?",
      option1: "John Lennon",
      option2: "Paul McCartney",
      option3: "Bob Dylan",
      option4: "Elton John",
      ans: 1,
      explain: "'Imagine' was written and performed by John Lennon in 1971.",
      difficulty: "medium",
    },
  ],

  
  sports: [
    {
      id: 1,
      question: "Which country has won the most FIFA World Cups?",
      option1: "Germany",
      option2: "Italy",
      option3: "Brazil",
      option4: "France",
      ans: 3,
      explain: "Brazil has won 5 World Cups — more than any other country.",
      difficulty: "medium",
    },
    {
      id: 2,
      question: "In basketball, how many players are on the court for one team?",
      option1: "4",
      option2: "5",
      option3: "6",
      option4: "7",
      ans: 2,
      explain: "Each basketball team has 5 players on the court at a time.",
      difficulty: "easy",
    },
    {
      id: 3,
      question: "Which tennis player has won the most Grand Slam titles (men)?",
      option1: "Novak Djokovic",
      option2: "Roger Federer",
      option3: "Rafael Nadal",
      option4: "Andy Murray",
      ans: 1,
      explain: "Djokovic holds the record for the most Grand Slam titles in men’s tennis.",
      difficulty: "hard",
    },
    {
      id: 4,
      question: "What sport is known as 'the gentleman’s game'?",
      option1: "Golf",
      option2: "Tennis",
      option3: "Cricket",
      option4: "Baseball",
      ans: 3,
      explain: "Cricket is often called 'the gentleman’s game' because of its sportsmanship traditions.",
      difficulty: "medium",
    },
    {
      id: 5,
      question: "In football, what is given for a serious foul?",
      option1: "Red card",
      option2: "Yellow card",
      option3: "Free kick",
      option4: "Corner kick",
      ans: 1,
      explain: "A red card means the player must leave the field immediately.",
      difficulty: "easy",
    },
  ],

  
  animals: [
    {
      id: 1,
      question: "What is the largest animal in the world?",
      option1: "Elephant",
      option2: "Blue Whale",
      option3: "Giraffe",
      option4: "Shark",
      ans: 2,
      explain: "The Blue Whale is the largest animal ever known to have lived on Earth.",
      difficulty: "easy",
    },
    {
      id: 2,
      question: "Which animal is known as the king of the jungle?",
      option1: "Tiger",
      option2: "Lion",
      option3: "Leopard",
      option4: "Cheetah",
      ans: 2,
      explain: "The lion is called the king of the jungle because of its strength and pride leadership.",
      difficulty: "easy",
    },
    {
      id: 3,
      question: "What do pandas mostly eat?",
      option1: "Grass",
      option2: "Bamboo",
      option3: "Fruits",
      option4: "Fish",
      ans: 2,
      explain: "Pandas’ main food is bamboo — it makes up about 99% of their diet.",
      difficulty: "medium",
    },
    {
      id: 4,
      question: "Which animal can sleep while standing?",
      option1: "Horse",
      option2: "Dog",
      option3: "Cat",
      option4: "Elephant",
      ans: 1,
      explain: "Horses can sleep standing up thanks to a special locking system in their legs.",
      difficulty: "medium",
    },
    {
      id: 5,
      question: "Which bird is famous for its colorful tail feathers?",
      option1: "Eagle",
      option2: "Parrot",
      option3: "Peacock",
      option4: "Ostrich",
      ans: 3,
      explain: "The peacock’s bright, colorful feathers are used in mating displays.",
      difficulty: "easy",
    },
  ],

  tvshows: [
  {
    question: "In which TV show is the character Walter White a chemistry teacher?",
    option1: "Breaking Bad",
    option2: "Better Call Saul",
    option3: "Narcos",
    option4: "The Wire",
    ans: 1,
  },
  {
    question: "Which show features a group called the 'Stranger Things'?",
    option1: "The X-Files",
    option2: "Stranger Things",
    option3: "Dark",
    option4: "Black Mirror",
    ans: 2,
  },
  {
    question: "What city is the setting for the show 'Friends'?",
    option1: "Chicago",
    option2: "New York",
    option3: "Los Angeles",
    option4: "Miami",
    ans: 2,
  },
  {
    question: "Who is the main character in 'Sherlock' TV series?",
    option1: "John Watson",
    option2: "Sherlock Holmes",
    option3: "Mycroft Holmes",
    option4: "James Moriarty",
    ans: 2,
  },
  {
    question: "Which TV show is about the politics in Westeros?",
    option1: "Vikings",
    option2: "Game of Thrones",
    option3: "The Witcher",
    option4: "The Crown",
    ans: 2,
  },
],

movies : [
  {
    question: "Who directed the movie 'Inception'?",
    option1: "Steven Spielberg",
    option2: "Christopher Nolan",
    option3: "James Cameron",
    option4: "Quentin Tarantino",
    ans: 2,
  },
  {
    question: "Which movie features a character named 'Forrest Gump'?",
    option1: "Cast Away",
    option2: "Saving Private Ryan",
    option3: "Forrest Gump",
    option4: "The Green Mile",
    ans: 3,
  },
  {
    question: "Which movie series is about a wizard named Harry Potter?",
    option1: "The Hunger Games",
    option2: "Lord of the Rings",
    option3: "Harry Potter",
    option4: "Percy Jackson",
    ans: 3,
  },
  {
    question: "Who played the role of Jack in the movie 'Titanic'?",
    option1: "Leonardo DiCaprio",
    option2: "Brad Pitt",
    option3: "Johnny Depp",
    option4: "Tom Cruise",
    ans: 1,
  },
  {
    question: "What is the name of the spaceship in 'Star Wars'?",
    option1: "Enterprise",
    option2: "Millennium Falcon",
    option3: "Galactica",
    option4: "Serenity",
    ans: 2,
  },
],

celebrities :  [
  {
    question: "Which actor played Iron Man in Marvel movies?",
    option1: "Chris Evans",
    option2: "Robert Downey Jr.",
    option3: "Chris Hemsworth",
    option4: "Mark Ruffalo",
    ans: 2,
  },
  {
    question: "Who is known as the 'King of Pop'?",
    option1: "Elvis Presley",
    option2: "Michael Jackson",
    option3: "Prince",
    option4: "Justin Bieber",
    ans: 2,
  },
  {
    question: "Which singer is famous for the song 'Hello'?",
    option1: "Adele",
    option2: "Taylor Swift",
    option3: "Beyoncé",
    option4: "Rihanna",
    ans: 1,
  },
  {
    question: "Who is the richest actor in the world?",
    option1: "Dwayne Johnson",
    option2: "Tom Cruise",
    option3: "Shah Rukh Khan",
    option4: "George Clooney",
    ans: 4,
  },
  {
    question: "Which celebrity is known for the reality show 'Keeping Up with the Kardashians'?",
    option1: "Kim Kardashian",
    option2: "Paris Hilton",
    option3: "Kylie Jenner",
    option4: "Kourtney Kardashian",
    ans: 1,
  },
],

history : [
  {
    question: "Who was the first President of the United States?",
    option1: "Thomas Jefferson",
    option2: "George Washington",
    option3: "Abraham Lincoln",
    option4: "John Adams",
    ans: 2,
  },
  {
    question: "In which year did World War II end?",
    option1: "1943",
    option2: "1944",
    option3: "1945",
    option4: "1946",
    ans: 3,
  },
  {
    question: "Which ancient civilization built the pyramids?",
    option1: "Romans",
    option2: "Greeks",
    option3: "Egyptians",
    option4: "Babylonians",
    ans: 3,
  },
  {
    question: "Who discovered America in 1492?",
    option1: "Vasco da Gama",
    option2: "Christopher Columbus",
    option3: "Ferdinand Magellan",
    option4: "Marco Polo",
    ans: 2,
  },
  {
    question: "What was the name of the ship that carried the Pilgrims to America?",
    option1: "Mayflower",
    option2: "Santa Maria",
    option3: "Endeavour",
    option4: "Beagle",
    ans: 1,
  },
],

geography:  [
  {
    question: "What is the largest country in the world by area?",
    option1: "Canada",
    option2: "China",
    option3: "Russia",
    option4: "USA",
    ans: 3,
  },
  {
    question: "Which continent has the most countries?",
    option1: "Africa",
    option2: "Asia",
    option3: "Europe",
    option4: "South America",
    ans: 1,
  },
  {
    question: "What is the capital city of Australia?",
    option1: "Sydney",
    option2: "Melbourne",
    option3: "Canberra",
    option4: "Brisbane",
    ans: 3,
  },
  {
    question: "Which river is the longest in the world?",
    option1: "Amazon",
    option2: "Nile",
    option3: "Yangtze",
    option4: "Mississippi",
    ans: 2,
  },
  {
    question: "Mount Everest is located in which mountain range?",
    option1: "Andes",
    option2: "Rocky Mountains",
    option3: "Himalayas",
    option4: "Alps",
    ans: 3,
  },
],

nature:  [
  {
    question: "What process do plants use to make food from sunlight?",
    option1: "Respiration",
    option2: "Photosynthesis",
    option3: "Transpiration",
    option4: "Germination",
    ans: 2,
  },
  {
    question: "Which gas do plants take from the air?",
    option1: "Oxygen",
    option2: "Carbon Dioxide",
    option3: "Nitrogen",
    option4: "Hydrogen",
    ans: 2,
  },
  {
    question: "What is the largest type of tree?",
    option1: "Oak",
    option2: "Redwood",
    option3: "Pine",
    option4: "Maple",
    ans: 2,
  },
  {
    question: "What is the main source of energy for life on Earth?",
    option1: "Water",
    option2: "Sun",
    option3: "Wind",
    option4: "Soil",
    ans: 2,
  },
  {
    question: "Which animal is known for changing colors?",
    option1: "Chameleon",
    option2: "Octopus",
    option3: "Cuttlefish",
    option4: "All of the above",
    ans: 4,
  },
],

universe:  [
  {
    question: "What is the closest planet to the Sun?",
    option1: "Venus",
    option2: "Earth",
    option3: "Mercury",
    option4: "Mars",
    ans: 3,
  },
  {
    question: "What is the name of our galaxy?",
    option1: "Andromeda",
    option2: "Milky Way",
    option3: "Whirlpool",
    option4: "Sombrero",
    ans: 2,
  },
  {
    question: "What force keeps planets orbiting the sun?",
    option1: "Magnetism",
    option2: "Gravity",
    option3: "Friction",
    option4: "Electricity",
    ans: 2,
  },
  {
    question: "Which planet is known as the Red Planet?",
    option1: "Mars",
    option2: "Jupiter",
    option3: "Saturn",
    option4: "Venus",
    ans: 1,
  },
  {
    question: "What is a star that suddenly gets very bright and then fades called?",
    option1: "Comet",
    option2: "Nova",
    option3: "Black hole",
    option4: "Nebula",
    ans: 2,
  },
],

economy:  [
  {
    question: "What does GDP stand for?",
    option1: "Gross Domestic Product",
    option2: "Global Debt Price",
    option3: "Gross Development Plan",
    option4: "General Domestic Price",
    ans: 1,
  },
  {
    question: "What is inflation?",
    option1: "Prices going up",
    option2: "Prices going down",
    option3: "Stable prices",
    option4: "No prices",
    ans: 1,
  },
  {
    question: "Which currency is used in Japan?",
    option1: "Yuan",
    option2: "Yen",
    option3: "Won",
    option4: "Dollar",
    ans: 2,
  },
  {
    question: "What is a stock?",
    option1: "A type of bond",
    option2: "Part ownership in a company",
    option3: "A loan",
    option4: "A savings account",
    ans: 2,
  },
  {
    question: "What does 'recession' mean?",
    option1: "Economic growth",
    option2: "Economic decline",
    option3: "Stable economy",
    option4: "High inflation",
    ans: 2,
  },
],

webdevelopment:  [
  {
    question: "What does HTML stand for?",
    option1: "Hyper Trainer Marking Language",
    option2: "Hyper Text Markup Language",
    option3: "Hyper Text Marketing Language",
    option4: "Hyper Text Markup Level",
    ans: 2,
  },
  {
    question: "Which language is used to style web pages?",
    option1: "HTML",
    option2: "JavaScript",
    option3: "CSS",
    option4: "Python",
    ans: 3,
  },
  {
    question: "What is React?",
    option1: "A backend language",
    option2: "A JavaScript library",
    option3: "A database",
    option4: "A framework",
    ans: 2,
  },
  {
    question: "Which symbol is used for comments in JavaScript?",
    option1: "//",
    option2: "/* */",
    option3: "#",
    option4: "<!-- -->",
    ans: 1,
  },
  {
    question: "What does CSS stand for?",
    option1: "Computer Style Sheets",
    option2: "Creative Style Sheets",
    option3: "Cascading Style Sheets",
    option4: "Colorful Style Sheets",
    ans: 3,
  },
],

science:  [
  {
    question: "What is the chemical symbol for water?",
    option1: "O2",
    option2: "CO2",
    option3: "H2O",
    option4: "NaCl",
    ans: 3,
  },
  {
    question: "What planet is known as the Red Planet?",
    option1: "Venus",
    option2: "Mars",
    option3: "Jupiter",
    option4: "Saturn",
    ans: 2,
  },
  {
    question: "What gas do humans need to breathe?",
    option1: "Carbon Dioxide",
    option2: "Oxygen",
    option3: "Nitrogen",
    option4: "Hydrogen",
    ans: 2,
  },
  {
    question: "How many bones are in the adult human body?",
    option1: "206",
    option2: "201",
    option3: "208",
    option4: "210",
    ans: 1,
  },
  {
    question: "What force pulls objects toward the Earth?",
    option1: "Magnetism",
    option2: "Gravity",
    option3: "Friction",
    option4: "Electricity",
    ans: 2,
  },
],

englishvocabulary:  [
  {
    question: "What does 'benevolent' mean?",
    option1: "Kind and good",
    option2: "Evil and cruel",
    option3: "Lazy and slow",
    option4: "Strong and brave",
    ans: 1,
  },
  {
    question: "What is the opposite of 'scarce'?",
    option1: "Rare",
    option2: "Abundant",
    option3: "Empty",
    option4: "Little",
    ans: 2,
  },
  {
    question: "What does 'ambiguous' mean?",
    option1: "Clear",
    option2: "Uncertain or unclear",
    option3: "Fast",
    option4: "Old",
    ans: 2,
  },
  {
    question: "What does 'frugal' mean?",
    option1: "Wasteful",
    option2: "Careful with money",
    option3: "Happy",
    option4: "Lazy",
    ans: 2,
  },
  {
    question: "What is a synonym for 'happy'?",
    option1: "Sad",
    option2: "Joyful",
    option3: "Angry",
    option4: "Tired",
    ans: 2,
  },
],

videogames : [
  {
    question: "Which game is known as the 'Battle Royale' game?",
    option1: "Minecraft",
    option2: "Fortnite",
    option3: "Call of Duty",
    option4: "Overwatch",
    ans: 2,
  },
  {
    question: "Who is the main character in 'The Legend of Zelda'?",
    option1: "Zelda",
    option2: "Link",
    option3: "Ganon",
    option4: "Mario",
    ans: 2,
  },
  {
    question: "Which company made the game 'Halo'?",
    option1: "Sony",
    option2: "Microsoft",
    option3: "Nintendo",
    option4: "EA",
    ans: 2,
  },
  {
    question: "In which game do players build with blocks?",
    option1: "Roblox",
    option2: "Minecraft",
    option3: "Terraria",
    option4: "Fortnite",
    ans: 2,
  },
  {
    question: "What is the currency used in 'Fortnite'?",
    option1: "Coins",
    option2: "V-Bucks",
    option3: "Gems",
    option4: "Gold",
    ans: 2,
  },
]

 
};


export default quizzes;
